language: node_js
node_js:
  - "8"

install:
  - npm install
  - (cd shins && npm install)

script:
  - npm run build-shins

deploy:
  provider: pages
  local-dir: ./docs
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
