swagger: '2.0'
info:
  $ref: ./info/_index.yaml
host: 'localhost:8080'
basePath: '/api'
tags:
  - name: Accounts
    description: Register, Login and Get/Set user profiles.
  - name: Clients
    description: Create, get and update application clients. Without one you can't send/receive/broadcast websocket messages.
  - name: Streams
    description: Create, get and update streams.
  - name: Stream Layers Collection
    description: Modify the stream's layer collection.
  - name: Stream Layer
    description: Modify a stream's specific layer.
  - name: Layer Objects Collection
    description: Add, remove objects to a specific layer in the stream.
  - name: Stream Objects Collection
    description: Directly operate on the objects in the stream.
  - name: Objects
    description: Directly CRUD objects in the database. They are not part of streams, and, as such, kindof suck.
  - name: Special Ops
    description: Extra lvl 5 magic spells.
schemes:
  - http
  - https
consumes: 
  - application/json
produces:
  - application/json
security: 
  - JWT Token Auth: []
securityDefinitions:
  JWT Token Auth:
    type: apiKey
    name: Authorization
    in: header
paths:
  $ref: ./paths/_index.yaml
definitions:
  $ref: ./definitions/_index.yaml